### ISSUE TITLE
Docker hub image?

### ISSUE THREAD

**Issue by juanluisbaptiste** [calvintam236/minergate-cli#1]
Hi,

Is this image available at docker hub ? if not have you planned pushing it ?

**Comment by calvintam236** [comment]
@juanluisbaptiste I did few months ago, but since minergate is infamous on stealing hashrate (and they haven't update it for a long time), I took it down. Just clone this and build it by `docker build . --tag calvintam236/minergate-cli:nvidia`.

**Comment by juanluisbaptiste** [comment]
Ahh ok, I didn't know that. So what other miner are you using now ?

**Comment by calvintam236** [comment]
@juanluisbaptiste I'm using `xmrig` right now with 1% fee, or you can try `xmr-stak` as well. I just like `xmrig` for the better UI and higher hashrate.

**Comment by juanluisbaptiste** [comment]
thank you.
